require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/email_files", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EmailFile. As you add validations to EmailFile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EmailFile.create! valid_attributes
      get email_files_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      email_file = EmailFile.create! valid_attributes
      get email_file_url(email_file)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_email_file_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      email_file = EmailFile.create! valid_attributes
      get edit_email_file_url(email_file)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EmailFile" do
        expect {
          post email_files_url, params: { email_file: valid_attributes }
        }.to change(EmailFile, :count).by(1)
      end

      it "redirects to the created email_file" do
        post email_files_url, params: { email_file: valid_attributes }
        expect(response).to redirect_to(email_file_url(EmailFile.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EmailFile" do
        expect {
          post email_files_url, params: { email_file: invalid_attributes }
        }.to change(EmailFile, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post email_files_url, params: { email_file: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested email_file" do
        email_file = EmailFile.create! valid_attributes
        patch email_file_url(email_file), params: { email_file: new_attributes }
        email_file.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the email_file" do
        email_file = EmailFile.create! valid_attributes
        patch email_file_url(email_file), params: { email_file: new_attributes }
        email_file.reload
        expect(response).to redirect_to(email_file_url(email_file))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        email_file = EmailFile.create! valid_attributes
        patch email_file_url(email_file), params: { email_file: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested email_file" do
      email_file = EmailFile.create! valid_attributes
      expect {
        delete email_file_url(email_file)
      }.to change(EmailFile, :count).by(-1)
    end

    it "redirects to the email_files list" do
      email_file = EmailFile.create! valid_attributes
      delete email_file_url(email_file)
      expect(response).to redirect_to(email_files_url)
    end
  end
end
